name: text_style_preview_lint
description: text_style_preview_lint is a package to make using text_style_preview more comfortable.
version: 0.2.0+2
homepage: https://twitter.com/K9i_apps
repository: https://github.com/K9i-0/text_style_preview

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  custom_lint_builder: ^0.3.3
  analyzer: ^5.2.0