name: text_style_preview
description: Preview a TextStyle based on Material Design's Typography. No more confusion in scale selection.
version: 0.1.4
homepage: https://twitter.com/K9i_apps
repository: https://github.com/K9i-0/text_style_preview

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: 'Simple demo'
    path: text_style_preview.gif

flutter: