name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  text_style_preview:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.3.3
  text_style_preview_lint:
    path: ../../text_style_preview_lint
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true